
export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";
export const GET_DATA_PER_PAGE = " GET_DATA_PER_PAGE";
export const GET_ACTIVE_COUNT = "GET_ACTIVE_COUNT";

export const GET_MODAL_ACTIVE = "GET_MODAL_ACTIVE";
export const GET_MODAL_INACTIVE = "GET_MODAL_INACTIVE";

export const SET_TIMESHEET_DATA = "SET_TIMESHEET_DATA"
export const SET_TIMESHEET_DATA_ERR = "SET_TIMESHEET_DATA_ERR"

export const SET_SIDEBAR_COLLAPS_ACTIVE = "SET_SIDEBAR_COLLAPS_ACTIVE"
export const SET_SIDEBAR_COLLAPS_DEACTIVE = "SET_SIDEBAR_COLLAPS_DEACTIVE"
export const SET_SIDEBAR_ITEM="SET_SIDEBAR_ITEM"