const dummyData = [
  {
    Projects: "Studio a+i Digital Marketing",
    ProjectOwner: "Rajesh Chandra",
    ProjectCode: "PC101",
    AccountCode: "PAC101",
    EngagementType: "Fixed",
    ProjectHealth: 1,
    HoursLogged: "110h 15m",
    BilledHours: "00h",
    Status: 2,
  },
  {
    Projects: "MDA Development & Marketing",
    ProjectOwner: "Rahul Mehra",
    ProjectCode: "PC102",
    AccountCode: "PAC102",
    EngagementType: "Dedicated",
    ProjectHealth: 2,
    HoursLogged: "120h 20m",
    BilledHours: "160h",
    Status: 1,
  },
  {
    Projects: "HIRED Schools Web Design & DM",
    ProjectOwner: "Himanshu Jindal",
    ProjectCode: "PC103",
    AccountCode: "PAC103",
    EngagementType: "Fixed",
    ProjectHealth: 3,
    HoursLogged: "180h 10m",
    BilledHours: "00h",
    Status: 2,
  },
  {
    Projects: "Clock Store Marketing",
    ProjectOwner: "Amit Chaudhary",
    ProjectCode: "PC104",
    AccountCode: "PAC104",
    EngagementType: "Fixed",
    ProjectHealth: 1,
    HoursLogged: "75h 30m",
    BilledHours: "190h",
    Status: 1,
  },
  {
    Projects: "Upright HC - Digital Marketing ",
    ProjectOwner: "Gagandeep Singh",
    ProjectCode: "PC105",
    AccountCode: "PAC105",
    EngagementType: "Dedicated",
    ProjectHealth: 2,
    HoursLogged: "225h 20m",
    BilledHours: "00h",
    Status: 2,
  },
];
export default dummyData;
